# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps-deployment.yaml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mli <mli@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/19 20:13:53 by mli               #+#    #+#              #
#    Updated: 2020/07/29 17:18:50 by mli              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

kind: Service
apiVersion: v1
metadata:
  name: ftps-service
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    app: ft_services
  ports:
    - name: ftp-connection
      port: 21
    - name: ftp-data
      port: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ft_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
      restartPolicy: Always
