apiVersion: v1
kind: Service
metadata:
  name: mysql-wp
  labels:
    app: ft_services-wordpress
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql
  selector:
    app: ft_services-wordpress
    tier: mysql
    #  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ft_services-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: ft_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: sqlpassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
