# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx-deployment.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mli <mli@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/19 20:13:53 by mli               #+#    #+#              #
#    Updated: 2020/07/25 12:31:58 by mli              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    app: ft_services
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ssh
      port: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ft_services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ft_services
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      containers:
      - name: nginx
        image: nginx-img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
