apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - name: wordpress
      port: 5050
      targetPort: 5050
  selector:
    app: ft_services
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ft_services-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: ft_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          value: wordpress
        - name: DB_USER
          value: mysql
        - name: DB_PASSWORD
          value: sqlpassword
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
